"""
rag_engine.py  —  auto-generated by fix_paths.py
Absolute paths are baked in so CWD never matters.
"""

import os
import requests
from pathlib import Path
from typing import List, Optional

try:
    from dotenv import load_dotenv
    load_dotenv(Path(r"C:\Users\cmith\Pictures\PHOTOS\OneDrive\Documents\HOSP-RAG") / ".env")
except Exception:
    pass

from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.document_loaders import TextLoader, PyPDFLoader
from langchain_community.vectorstores import FAISS
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain.schema import Document

# ── Config ────────────────────────────────────────────────────────────────────
OPENROUTER_API_KEY  = os.getenv("OPENROUTER_API_KEY", "")
OPENROUTER_BASE_URL = os.getenv("OPENROUTER_BASE_URL", "https://openrouter.ai/api/v1")
MODEL_NAME          = os.getenv("MODEL_NAME",      "mistralai/mixtral-8x7b-instruct")
EMBEDDING_MODEL     = os.getenv("EMBEDDING_MODEL", "all-MiniLM-L6-v2")

# Absolute paths — never break regardless of CWD
DOCUMENTS_DIR   = r"C:\Users\cmith\Pictures\PHOTOS\OneDrive\Documents\HOSP-RAG\data\documents"
FAISS_INDEX_DIR = r"C:\Users\cmith\Pictures\PHOTOS\OneDrive\Documents\HOSP-RAG\data\faiss_index"

AVAILABLE_MODELS = [
    "mistralai/mixtral-8x7b-instruct",
    "mistralai/mistral-7b-instruct",
    "meta-llama/llama-3-70b-instruct",
    "meta-llama/llama-3-8b-instruct",
    "openai/gpt-3.5-turbo",
    "openai/gpt-4o-mini",
    "anthropic/claude-3-haiku",
    "google/gemma-2-9b-it",
]


def get_embedding_function():
    return HuggingFaceEmbeddings(
        model_name=EMBEDDING_MODEL,
        model_kwargs={"device": "cpu"},
        encode_kwargs={"normalize_embeddings": True},
    )


def load_documents(docs_dir: str = None) -> List[Document]:
    p = Path(docs_dir).resolve() if docs_dir else Path(DOCUMENTS_DIR).resolve()
    if not p.exists():
        raise FileNotFoundError(f"Documents folder not found: {p}")
    
    docs = []
    for f in list(p.glob("**/*.txt")) + list(p.glob("**/*.pdf")):
        try:
            loader = TextLoader(str(f), encoding="utf-8") if f.suffix == ".txt" else PyPDFLoader(str(f))
            for doc in loader.load():
                doc.metadata["filename"] = f.name
                docs.append(doc)
        except Exception as e:
            print(f"Skipping {f.name}: {e}")
    
    if not docs:
        raise ValueError(f"No .txt or .pdf files found in {p}")
    
    print(f"Loaded {len(docs)} sections from {p}")
    return docs


def chunk_documents(documents: List[Document]) -> List[Document]:
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=800, chunk_overlap=150,
        separators=["\n\n", "\n", ".", " ", ""],
    )
    chunks = splitter.split_documents(documents)
    print(f"Created {len(chunks)} chunks")
    return chunks


def build_vectorstore(chunks: List[Document], index_dir: str = None) -> FAISS:
    idx = Path(index_dir).resolve() if index_dir else Path(FAISS_INDEX_DIR).resolve()
    idx.mkdir(parents=True, exist_ok=True)
    vs = FAISS.from_documents(chunks, get_embedding_function())
    vs.save_local(str(idx))
    print(f"FAISS index saved to {idx}")
    return vs


def load_vectorstore(index_dir: str = None) -> Optional[FAISS]:
    idx = Path(index_dir).resolve() if index_dir else Path(FAISS_INDEX_DIR).resolve()
    if not idx.exists() or not any(idx.iterdir()):
        return None
    try:
        return FAISS.load_local(str(idx), get_embedding_function(), allow_dangerous_deserialization=True)
    except Exception as e:
        print(f"Could not load index: {e}")
        return None


def initialize_rag(force_rebuild: bool = False) -> FAISS:
    if not force_rebuild:
        vs = load_vectorstore()
        if vs:
            return vs
    docs   = load_documents()
    chunks = chunk_documents(docs)
    return build_vectorstore(chunks)


def retrieve_context(vectorstore: FAISS, query: str, k: int = 5) -> List[Document]:
    return vectorstore.similarity_search(query, k=k)


def format_context(docs: List[Document]) -> str:
    return "\n\n---\n\n".join(
        f"[Source {i}: {doc.metadata.get('filename','?')}]\n{doc.page_content.strip()}"
        for i, doc in enumerate(docs, 1)
    )


def call_openrouter(messages: list, model: str = MODEL_NAME,
                    temperature: float = 0.2, max_tokens: int = 1024) -> str:
    key = OPENROUTER_API_KEY or os.getenv("OPENROUTER_API_KEY", "")
    if not key:
        raise ValueError("OPENROUTER_API_KEY not set")
    r = requests.post(
        f"{OPENROUTER_BASE_URL}/chat/completions",
        headers={"Authorization": f"Bearer {key}", "Content-Type": "application/json",
                  "HTTP-Referer": "https://hospital-rag.internal", "X-Title": "MedBot"},
        json={"model": model, "messages": messages, "temperature": temperature, "max_tokens": max_tokens},
        timeout=60,
    )
    if r.status_code != 200:
        raise Exception(f"OpenRouter {r.status_code}: {r.text}")
    return r.json()["choices"][0]["message"]["content"]


SYSTEM_PROMPT = """You are MedBot, an expert hospital knowledge assistant for internal staff.
Answer ONLY from the provided document context. Use numbered steps for procedures.
Always name the source document. If not found say: This is not in the hospital documents."""


def answer_question(vectorstore: FAISS, question: str,
                    chat_history: List[dict] = None,
                    model: str = MODEL_NAME, k: int = 5) -> dict:
    docs    = retrieve_context(vectorstore, question, k=k)
    context = format_context(docs)
    msgs    = [{"role": "system", "content": SYSTEM_PROMPT}]
    if chat_history:
        msgs.extend(chat_history[-8:])
    msgs.append({"role": "user", "content": f"CONTEXT:\n{context}\n\nQUESTION: {question}"})
    answer  = call_openrouter(msgs, model=model)
    sources = list({d.metadata.get("filename", "?") for d in docs})
    return {"answer": answer, "sources": sources, "context_docs": docs}


def get_document_stats(docs_dir: str = None) -> dict:
    p   = Path(docs_dir).resolve() if docs_dir else Path(DOCUMENTS_DIR).resolve()
    txt = list(p.glob("**/*.txt")) if p.exists() else []
    pdf = list(p.glob("**/*.pdf")) if p.exists() else []
    return {
        "total_files": len(txt) + len(pdf),
        "txt_files":   len(txt),
        "pdf_files":   len(pdf),
        "filenames":   [f.name for f in txt + pdf],
        "docs_path":   str(p),
    }
