[server]
address = "localhost"
port = 8501
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
backgroundColor = "#071a1a"
secondaryBackgroundColor = "#0d2626"
textColor = "#e2fafa"
primaryColor = "#0d9488"